FROM nginx
MAINTAINER Docker antscript <antscript@gmail.com>

RUN apt-get update && apt-get install -y ca-certificates git-core ssh


RUN mkdir /root/.ssh/
RUN ssh-keyscan -t rsa bitbucket.org > ~/.ssh/known_hosts
ADD temp/id_rsa /root/.ssh/id_rsa
ADD temp/id_rsa.pub /root/.ssh/id_rsa.pub
RUN chmod 600 /root/.ssh/*

ARG GIT_URL=your_git_url
RUN mkdir -p /data/DockerWeb/
WORKDIR /data
RUN git clone $GIT_URL /data/DockerWeb/


WORKDIR /data/DockerWeb
RUN git checkout master

ADD temp/ssl.crt /data/https/ssl.crt
ADD temp/ssl.key /data/https/ssl.key

RUN rm /etc/nginx/nginx.conf
ADD temp/nginx.conf /etc/nginx/nginx.conf

RUN rm /etc/nginx/conf.d/default.conf
ADD temp/default.conf /etc/nginx/conf.d/default.conf

ADD temp/hooks.json /data/conf/hooks.json

ADD temp/start.sh /data/script/start.sh
RUN chmod +x /data/script/start.sh
CMD ["sh","/data/script/start.sh"]